name: Common Secret Sync

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: "echo Hello from reusable workflow: ${{ inputs.message }}"
